// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqAnpxysLNHN-TF8vfsyU_VH-9dcwVtWc',
    appId: '1:416768108989:web:b2debaca3007e749cb8ad4',
    messagingSenderId: '416768108989',
    projectId: 'project-fasum',
    authDomain: 'project-fasum.firebaseapp.com',
    storageBucket: 'project-fasum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdzmV9--wtk-YlJzUiZgL87WVXgDUAv3I',
    appId: '1:416768108989:android:dcb157c6b440a9aecb8ad4',
    messagingSenderId: '416768108989',
    projectId: 'project-fasum',
    storageBucket: 'project-fasum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABLoOGDXcLkQkoxs6Zb0EZF2b9WK5GJW8',
    appId: '1:416768108989:ios:4eaf2ba90fbe5c2ccb8ad4',
    messagingSenderId: '416768108989',
    projectId: 'project-fasum',
    storageBucket: 'project-fasum.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABLoOGDXcLkQkoxs6Zb0EZF2b9WK5GJW8',
    appId: '1:416768108989:ios:4eaf2ba90fbe5c2ccb8ad4',
    messagingSenderId: '416768108989',
    projectId: 'project-fasum',
    storageBucket: 'project-fasum.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqAnpxysLNHN-TF8vfsyU_VH-9dcwVtWc',
    appId: '1:416768108989:web:c0ce3855bb45d226cb8ad4',
    messagingSenderId: '416768108989',
    projectId: 'project-fasum',
    authDomain: 'project-fasum.firebaseapp.com',
    storageBucket: 'project-fasum.firebasestorage.app',
  );
}
